language: cpp
compiler:
  - gcc
  - clang
before_script:
  - mkdir ../build
  - cd ../build
script:
  - cmake ../Arithmetic
  - make -j
  - ls
  - ./test/Arithmetic_Test
notifications:
  email: false
